<?php

/**
 * My Application bootstrap file.
 */
use Nette\Application\Routers\Route;
use Nette\Diagnostics\Debugger;

// Load Nette Framework or autoloader generated by Composer
require LIBS_DIR . '/autoload.php';
//require LIBS_DIR . '/nette.min.php';

// Configure application
$configurator = new Nette\Config\Configurator;
//$configurator->setProductionMode(TRUE);

// Enable Nette Debugger for error visualisation & logging
//$configurator->setDebugMode($configurator::AUTO);
$configurator->enableDebugger(__DIR__ . '/../log');
//Debugger::enable(Debugger::PRODUCTION);

// Enable RobotLoader - this will load all classes automatically
$configurator->setTempDirectory(__DIR__ . '/../temp');
$configurator->createRobotLoader()
	->addDirectory(APP_DIR)
	->addDirectory(LIBS_DIR)
	->register();

// Create Dependency Injection container from config.neon file
$configurator->addConfig(__DIR__ . '/config/config.neon');
$container = $configurator->createContainer();


// error presenter setup
$application = $container->application;
$application->errorPresenter = 'Error';

// Setup router
$container->router[] = new Route('index.php', 'Homepage:default', Route::ONE_WAY);
$container->router[] = new Route('<presenter>[.html]/<action>', 'Homepage:default');

// Configure and run the application!
$container->application->run();